### ISSUE TITLE
데이터는 정확하지만 학습방법이 잘못됬습니다.

### ISSUE THREAD

**Issue by SaidBySolo** [wonderlandpark/girlfriend-predict-model#1]
변수를 추가해주시죠.

제가 평생 못사귈수도 있고 여친이 생길수도있죠

마치 그 슈뢰딩거의 고양이처럼요

아직 몰라요

보기 전 까지는...

**Comment by ghostdeleted** [comment]
학습 방법은 정확한것 같습니다

**Comment by wonderlandpark** [comment]
데이터에 변동사항이 있다면 데이터를 조절하여 학습하여주십시오
